services:
  - type: web
    name: web-animations-library
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: STATIC_DIR
        value: public
      - key: ASSETS_DIR
        value: animations
    staticPublishPath: ./public
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 